# Assignments Involving Reactions, Rates, and Rate Expressions

## Examples from *REB, The Book* {.ch}

**Example 2.6.1** Carbon monoxide (CO) can be oxidized by molecular oxygen (O~2~) to produce carbon dioxide (CO~2~). If equal volumes of carbon monoxide and air at equal temperature and pressure are mixed and flow into a chemical reactor, which reactant is limiting?

[Example 2.6.1 Solution](examples/2_6_2/Example%202.6.2.pdf)

---

**Example 2.6.2** A new reactor is being developed with the hope of generating ethylene by the oxidative dehydrogenation of ethane, reaction (1). Reactions (2) and (3) also take place at the operating conditions of 1 atm and 150 °C. The process starts with 90% ethane and 10% air (you may take air to contain 79% N~2~ and 21% O~2~) and ends with a 50% conversion of O~2~ and a selectivity of 3 C~2~H~4~/CO~2~. Calculate the final mole fraction of CO~2~.

$$
2 C_2H_6 + O_2 \leftrightarrows 2 C_2H_4 + 2 H_2O \tag{1}
$$

$$
C_2H_4 + 3 O_2 \leftrightarrows 2 CO_2 + 2 H_2O \tag{2}
$$

$$
2 C_2H_6 + 7 O_2 \leftrightarrows 4 CO_2 + 6 H_2O \tag{3}
$$

[Example 2.6.2 Solution](examples/2_6_2/Example%202.6.2.pdf)

---

**Example 2.6.3** Suppose gas-phase reaction (1) was studied in an open, steady-state, isothermal, isobaric system. The flow into the system contained 0.5 mol min^−1^ of N~2~O~5~ and 0.5 mol min^−1^ of N~2~ at 600 K and 5 MPa. 

(a) Write an equation for the outlet molar flow rate of NO~2~ in terms of the outlet molar flow rate of N~2~O~5~.
(b) If the outlet flow contains 30% N~2~, calculate the conversion of N~2~O~5~.

$$
2 N_2O_5 \leftrightarrows 4 NO_2 + O_2 \tag{1}
$$

[Example 2.6.3 Solution](examples/2_6_3/Example%202.6.3.pdf)

---

**Example 2.6.4** Suppose a system initially contains 1 mole of CH~4~ and 2.5 moles of H~2~O. Reactions (1) through (4) occur at 920 °C with 88% conversion of CH~4~ and a CO yield of 65%. Selected thermodynamic data are presented in @tbl-ch2_example4. Generate the necessary expressions for heats of reaction and use them to calculate the net heat released.

$$
CH_4 + H_2O \rightarrow CO + 3 H_2 \tag{1}
$$

$$
CH_4 + CO_2 \rightarrow 2 CO + 2 H_2 \tag{2}
$$

$$
CH_4 + 2 H_2O \rightarrow CO_2 + 4 H_2 \tag{3}
$$

$$
CO + H_2O \rightarrow CO_2 + H_2 \tag{4}
$$

| $i$ | $\Delta H_{f,i}\big\vert_{T=298K}$ | $\hat{C}_{p,i}$ |
|:-------:|:-------:|:-------:|
| CH~4~ | -17.89 | 4.598 + 1.245 x 10^-2^ T + 2.86 x 10^-6^ T^2^ - 2.703 x 10^-9^ T^3^ |
| H~2~O | -57.8 | 7.701 + 4.595 x 10^-4^ T + 5.521 x 10^-6^ T^2^ - 0.859 x 10^-9^ T^3^ |
| CO | -26.42 | 7.373 - 3.07 x 10^-3^ T + 6.662 x 10^-6^ T^2^ - 3.037 x 10^-9^ T^3^ |
| H~2~ | 0.0 | 6.483 + 2.215 x 10^-3^ T - 3.298 x 10^-6^ T^2^ + 1.826 x 10^-9^ T^3^ |
| CO~2~ | -94.05 | 4.728 + 1.754 x 10^-2^ T - 1.338 x 10^-5^ T^2^ + 4.097 x 10^-9^ T^3^ |

: Ideal gas standard heats of formation^1^ and heat capacities^2^ from @reid_properties_1977. {#tbl-ch2_example4 tbl-colwidths="[10,10,80]"}

^1^ kcal mol^-1^  
^2^ cal mol^-1^ K^-1^ for T in K

[Example 2.6.4 Solution](examples/2_6_4/Example%202.6.4.pdf)

---

**Example 3.6.1** The synthesis of ammonia, reaction (1), is one of the highest production chemical processes in the world. (One reason for this is that ammonia is used to make fertilizer.) It is a heterogeneous catalytic reaction. The ammonia synthesis catalyst takes the form of pellets that pack into the the reactor with an apparent density of 155 lb~m~ ft^-3^. Rase [-@rase_h_f_chemical_1977] provides the expression in equation (2) for the rate of generation of ammonia via reaction (1). In that expression, $E_1$ is the activation energy, $K_{1,eq}$ is the equilibrium constant and $a_i$ represents the thermodynamic activity of reagent $i$.

$$
3 H_2 + N_2 \rightleftarrows 2 NH_3 \tag{1}
$$

$$
\begin{align}
r_{NH_3,1} &= 1.54 \times 10^{15} \exp{\left( \frac{-E_1}{RT} \right)} \\
&\times \left[ K_{1,eq}^2\left( \frac{a_{N_2}a_{H_2}^{1.5}}{a_{NH_3}} \right) - \left( \frac{a_{NH_3}}{a_{H_2}^{1.5}} \right)  \right] \frac{\text{kmol NH}_3}{\text{m}_{\text{bed}}^3 \text{h}}
\end{align} \tag{2}
$$

Write an expression for the general rate of reaction (1), $r_1$, that is normalized per lb~m~ of catalyst.

[Example 3.6.1 Solution](examples/3_6_1/Example%203.6.1.pdf)

---

**Example 3.6.2** The water-gas shift, reaction (1), is used commercially to remove CO impurities from hydrogen. Suppose the rate expression shown in equation (2) was validated using experimental data that were far from thermodynamic equilibrium. At 675 K, the rate coefficient, $k_1$, was found to equal to 3.37 lbmol h^-1^ ft^-3^ atm^-0.55^. In equation (3), that power-law rate expression has been multiplied by a factor that will force it to evaluate to zero at equilibrium. At 675 K, the equilibrium constant, $K_1$ is equal to 12.0.

If a system initially containing 75% H~2~O, 24% CO, and 1% CO~2~ at 10 atm and 675 K reacts isothermally and isobarically, the equilibrium conversion of CO will equal 96.3%. The net rate should go to zero at this conversion.

$$
CO + H_2O \rightleftarrows CO_2 + H_2 \tag{1}
$$

$$
r_1 = k_1 P_{CO}^{0.9} P_{H_2O}^{0.25} P_{CO_2}^{-0.6} \tag{2}
$$

$$
r_1 = k_1 P_{CO}^{0.9} P_{H_2O}^{0.25} P_{CO_2}^{-0.6} \left\{ 1 - \frac{P_{CO_2} P_{H_2}}{K_1 P_{CO} P_{H_2O}} \right\} \tag{3}
$$

For the system described above, make a plot of the net rate of reaction (1) predicted by equations (2) and (3) at CO conversions between 0 and 100%. Then make a second plot at conversions between 85 and 100%. Comment upon the results.

[Example 3.6.2 Solution](examples/3_6_2/Example%203.6.2.pdf)

[Example 3.6.2 Calculations](examples/3_6_2/example_3_6_2.py)

---

**Example 3.6.3** Kinetic studies were performed at a number of different temperatures, $T$, to find the value of a second order rate coefficient, $k$, at those temperatures. The results for each experiment, $i$, are given in the table below. Determine whether the temperature dependence of this rate coefficient is consistent with the Arrhenius expression, and find the best values for the pre-exponential factor and the activation energy.

| i (Experiment Number) | T (°C) | k (L mol^–1^ min^–1^) |
|:------:|:-------:|:-------:|
| 1 | 10 | 2.63 $\times$ 10^-4^ |
| 2 | 22 | 4.78 $\times$ 10^-4^ |
| 3 | 40 | 1.52 $\times$ 10^-3^ |
| 4 | 54 | 4.18 $\times$ 10^-3^ |
| 5 | 65 | 9.07 $\times$ 10^-3^ |
| 6 | 78 | 2.14 $\times$ 10^-2^ |
| 7 | 89 | 4.2 $\times$ 10^-2^ |
| 8 | 103 | 9.42 $\times$ 10^-2^ |
  
: Rate coefficients measured experimentally at different temperatures. {#tbl-ch3_ex3_data}

The data are available in the .csv file, [example_3_6_3_data.csv](./solutions/ch3_ex3/example_3_6_3_data.csv).

[Example 3.6.3 Solution](examples/3_6_3/Example%203.6.3.pdf)

[Example 3.6.3 Calculations](examples/3_6_3/example_3_6_3.py)

---

**Example 3.6.4** The decomposition of HI, equation (1), is elementary. Collision theory predicts the rate coefficient to depend upon temperature as shown in equation (2) where $N_{av}$ is Avogadro's number and $k_B$ is the Boltzmann constant. The collision cross-section, $\sigma_{HI-HI}$, is 38.5 Å, the reduced mass, $\mu$, is 1.063 x 10^-22^ g, and the activation energy, $E$, is 184.1 kJ mol^-1^.

$$
2 HI \rightleftarrows H_2 + I_2 \tag{1}
$$

$$
k = N_{av}\sigma_{HI-HI} \sqrt{\frac{2k_BT}{\pi \mu}} \exp{\left( \frac{-E}{RT}\right)} \tag{2}
$$

Use equation (2) to calculate the rate coefficient at several temperatures between 300 and 400 K. Then use the resulting $\underline{k}$ *vs.* $\underline{T}$ data to assess how well the Arrhenius expression describes the rate coefficient.

[Example 3.6.4 Solution](examples/3_6_4/Example%203.6.4.pdf)

[Example 3.6.4 Calculations](examples/3_6_4/example_3_6_4.py)

## Learning Activities from *REB, The Course* {.ch}

**Learning Activity 2.1** A gas phase system initially contains 0.5 mol of N~2~O~5~ and 0.5 mol of NO~2~ at 600 K and 5 MPa. The N~2~O~5~ decomposes according to reaction (1). Write an expression for the amount of NO~2~ in terms of the amount of N~2~O~5~.

$$
2 N_2O_5 \leftrightarrows 4 NO_2 + O_2 \tag{1}
$$

[Activity 2.1 Solution](activities/class_2/Activity%202.1.pdf)

---

**Learning Activity 2.2** The gas phase reaction synthesis of ammonia from NO, reaction (1), takes place in a system that initially contained 2 moles of H~2~ and 1 mole of NO. If 50% of the limiting reactant was converted, what was the final mole fraction of ammonia?

$$
2 NO + 5 H_2 \leftrightarrows 2 NH_3 + 2 H_2O \tag{1}
$$

[Activity 2.2 Solution](activities/class_2/Activity%202.2.pdf)

---

**Learning Activity 2.3** The charge to a reactor consisted of 66 mol H~2~ and 34 mol CO. Reactions (1) through (6) occurred, after which 40% of the CO had been converted. The final ratio of H~2~ to CO was 1.5, and the selectivity for methanol over carbon dioxide was 8.3. Calculate the final molar amount of each reagent in the system.

$$
CO + 2 H_2 \rightleftarrows CH_3OH \tag{1}
$$

$$
CO_2 + 3 H_2 \rightleftarrows CH_3OH + H_2O \tag{2}
$$

$$
CO + H_2O \rightleftarrows CO_2 + H_2 \tag{3}
$$

$$
CO + 3 H_2 \rightleftarrows CH_4 + H_2O \tag{4}
$$

$$
CO_2 + 4 H_2 \rightleftarrows CH_4 + 2 H_2O \tag{5}
$$

$$
CH_4 + H_2O \rightleftarrows CH_3OH + H_2 \tag{6}
$$

[Activity 2.3 Solution](activities/class_2/Activity%202.3.pdf)

---

**Learning Activity 2.4** The vapor phase synthesis of methanol is given in reaction (1). The gas phase heat capacity of reagent $i$, $\hat{C}_{p,i}$, in J mol^-1^ K^-1^ can be calculated using equation (2) where $t$ is the temperature in K divided by 1000. The constants for use in equation (2), $A_i$ through $E_i$, are given in @tbl-ch2_activity4, which also includes the standard heat of formation at 298 K, the standard change in Gibbs free energy for formation, and the standard entropy of the reagents in kJ mol^-1^, kJ mol^-1^, and J mol^-1^ K^-1^, respectively. Generate an expression for the heat of reaction (1) as a function of temperature.

$$
CO + 2 H_2 \rightleftarrows CH_3OH \tag{1}
$$

$$
\hat{C}_{p,i} = A_i + B_i t + C_i t^2 + D_i t^3 + \frac{E_i}{t^2} \tag{2}
$$

| i | CO | H~2~ |CH~3~OH |
|:-------:|:-------:|:-------:|:-------:|
| A~i~ | 25.567590 | 33.107800 | 21.138073 |
| B~i~ | 6.096130 | -11.508000 | 70.878654 |
| C~i~ | 4.054656 | 11.609300 | 25.853554 |
| D~i~ | -2.671301 | -2.844400 | -28.497905 |
| E~i~ | 0.131021 | -0.159665 | 0.0 |
| $\Delta H_{f,i}\big\vert_{298K}$ | -110.53 | 0.0 | -201.0 |
| $\Delta G_{f,i}\big\vert_{298K}$ | -137.3689 | 0.0 | -162.6153 |
| $S_i^0$ | 197.6482155 | 130.6656268 | 239.7234884 |

: Thermodynamic data for Activity 4 from Chase, M. W., Jr., C. A. Davies, J. R. Downey, Jr., D. J. Frurip, R. A. McDonald and A. N. Syverud, “JANAF Thermochemical Tables,” 3rd ed. American Chemical Society and American Institute of Physics, New York, 1986. {#tbl-ch2_activity4}

[Activity 2.4 Solution](activities/class_2/Activity%202.4.pdf)

---

**Learning Activity 3** Reversible reaction (1) is elementary and the forward rate coefficient obeys the Arrhenius expression with a pre-exponential factor equal to 6.97 x 10^6^ L mol^–1^ min^–1^ and an activation energy equal to 57.3 kJ mol^–1^. Use the ideal gas law to replace the concentrations in the rate expression with partial pressures in atm, and combine the terms involving temperature into apparent forward and reverse rate coefficients.

$$
A + B \rightleftarrows C + D \tag{1}
$$

Write a utility function that takes the ideal gas constant and equal-sized arrays of absolute temperatures and rate coefficients as arguments and returns the pre-exponential factor and activation energy, their 95% confidence intervals (CIs), and the coefficient of determination. Add the function to reb_utils.py and use it to determine whether the apparent forward rate coefficient displays Arrhenius temperature dependence, and, if so, what are the best estimates for the pre-exponential factor and the activation energy at temperatures between 0 and 100 °C?


[Activity 3 Solution](activities/class_3/Activity%203.pdf)

[reb_utils.py](./code/reb_utils.py)

## Practice Assignments from *REB, The Course* {.ch}

**Practice Assignment 2.1** Cellulosic biomass, represented here as C~6~H~10~O~5~, can be gasified using steam. Reactions (1) through (3) take place. Suppose gasification began with 10 moles of H~2~O for every mole of C~6~H~10~O~5~, and no other reagents present. If 50% of the cellulose is converted and the selectivity for CO~2~ over CO is 3, what will the CO to H~2~ ratio equal?

$$
C_6H_{10}O_5 + 7 H_2O \rightarrow 6 CO_2 + 12 H_2 \tag{1}
$$

$$
C_6H_{10}O_5 + H_2O \rightarrow 6 CO + 6 H_2 \tag{2}
$$

$$
CO + H_2O \rightarrow CO_2 + H_2 \tag{3}
$$

[Practice Assignment 2.1 Solution](practice/class_2/Practice%20Assignment%202.1.pdf)

---

**Practice Assignment 2.2** The oxidation of ethanol to produce acetic acid is given in equation (1). Standard gas phase heats of formation at 298 K and heat capacities for the reagents are provided in @tbl-ch2_practice2. Generate an expression for the standard heat of reaction as a function of temperature and use it to calculate the standard heat of reaction at 300, 350, and 400 K.

$$
C_2H_5OH + O_2 \rightarrow CH_3COOH + H_2O \tag{1}
$$

| Reagent | $\Delta H_f\big\vert_{298K}$ (kJ mol^-1^) | $\hat{C}_p$ (J mol^-1^ K^-1^) |
|:-------:|:-------:|:-------:|
| C~2~H~6~O | -234 | 73.4 |
| C~2~H~4~O~2~ | -443 | 71.7 |
| H~2~O | -242 | 33.9 |
| O~2~ | 0 | 29.7 |

: Thermodynamic data for Practice Assignment 2.2. {#tbl-ch2_practice2}

[Practice Assignment 2.2 Solution](practice/class_2/Practice%20Assignment%202.2.pdf)

---

**Practice Assignment 3** A reaction was studied at the temperatures, $T$, listed in the @tbl-ch3_practice3_data, and at each temperature the value of the first-order rate coefficient, $k$, was determined. On the basis of the information provided in the table, does the rate coefficient display Arrhenius temperature dependence? If it does, what are the values of the pre-exponential factor and the activation energy? The data are also available in the file, [practice_3_data.csv](practice/class_3/practice_3_data.csv).

|T (°F) | k (s^-1^) |
|:-------:|:-------:|
| 76.7 | 1.12 $\times$ 10^5^ |
| 92.9 | 3.63 $\times$ 10^5^ |
| 114.5 | 1.15 $\times$ 10^-4^ |
| 132.5 | 3.26 $\times$ 10^-4^ |
| 148.7 | 8.92 $\times$ 10^-4^ |

: Rate coefficients measured experimentally at different temperatures for Practice Assignment 3. {#tbl-ch3_practice3_data}

[Practice Assignment 3 Solution](practice/class_3/Practice%20Assignment%203.pdf)

[Practice Assignment 3 Calculations](practice/class_3/practice_3.py)

## Additional Assignments for Extra Practice {.ch}

Additional assignments will be added as they become available.

## References
