# Assignments Involving Analysis of Reactor Systems

## Examples from *REB, The Book* {.ch}

**Example 12.4.1** A 350 L adiabatic CSTR and a 350 L adiabatic PFR are going to be connected in series and used to convert reagent A according to irreversible reactions (1) and (2), where D is the desired product and U is an undesired, low-value byproduct. The feed consists of an aqueous stream containing 2.5 mol A L^-1^, flowing at a rate of 100 L min^-1^ at 38 °C. The liquid density may be assumed to be constant. The heat of reaction (1) is -21,500 cal mol^-1^ and that of reaction (2) is -24,000 cal mol^-1^. The heat capacity of the solution is constant and equal to 1.0 cal cm^-3^ K^-1^. The rate expressions for reactions (1) and (2) are given in equations (3), and (4), respectively. The pre-exponential factor for reaction (3) is 1.2 x 10^5^ min^-1^, and the activation energy is 9100 cal mol^-1^. The Arrhenius parameters for reaction (4) are 2.17 x 10^7^ L mol^-1^ min^-1^ and 13,400 cal mol^-1^. Compare the overall conversion of A and selectivity (mol D per mol U) for the configuration with the CSTR first to those with the PFR first.

$$
A \rightarrow D \tag{1}
$$
$$
A \rightarrow U \tag{2}
$$

$$
r_1 = k_1 C_A \tag{3}
$$

$$
r_1 = k_1 C_A^2 \tag{4}
$$

[Example 12.4.1 Solution](examples/12_4_1/Example%2012.4.1.pdf)

[Example 12.4.1 Calculations](examples/12_4_1/example_12_4_1.py)

---

**Example 12.4.2** The water-gas shift reaction, equation (1), is exothermic, $\Delta H$ = –9120 cal mol^-1^, and reversible. The equilibrium constant can be approximated using equation (2) with $K_{0,1}$ = 0.132. The heat capacities of CO, H~2~O, CO~2~, H~2~, and inert, I, can be taken to be constant and equal to 29.3, 34.3, 41.3, 29.2, and 40.5 J mol^-1^ K^-1^, respectively. Two packed bed reactors in series are used to process a feed consisting of 1 mol CO h^-1^, 0.359 mol CO~2~ h^-1^, 4.44 mol H~2~ h^-1^, 0.180 mol I h^-1^, and 9.32 mol H~2~O h^-1^ at 26 atm and 445 °C. The volume of the first packed bed is 685 cm^3^, and it is packed with a high-temperature catalyst for which the rate is given by equation (3) with $k_{0,1}$ = 0.0354 mol cm^-3^ min^-1^ atm^-2^ and $E_1$ = 9740 cal mol^-1^. The product stream leaving the first packed bed passes through a heat exchanger. Chilled water at 20 °C flowing at a rate of 1100 g/h enters the other side of the heat exchanger and exits the heat exchanger at 50 °C The volume of the second packed bed is 3950 cm^3^, and the packing is a low-temperature catalyst for which the rate also is given by equation (3), but  with $k_{0,1}$ = 1.77 x 10^-3^ mol cm^-3^ min^-1^ atm^-2^ and $E_1$ = 3690 cal mol^-1^. Pressure drop in the reactors is negligible. What are the overall conversion of CO and the temperature of the product gas leaving the second packed bed reactor?

$$
CO + H_2O \rightleftarrows CO_2 + H_2 \tag{1}
$$

$$
K = K_0 \exp{ \left( \frac{-\Delta H}{RT} \right)} \tag{2}
$$

$$
r = k \left( P_{CO} P_{H_2O} - \frac{P_{CO_2}P_{H_2}}{K} \right) \tag{3}
$$

[Example 12.4.2 Solution](examples/12_4_2/Example%2012.4.2.pdf)

[Example 12.4.2 Calculations](examples/12_4_2/example_12_4_2.py)

---

**Example 12.4.3** An aqueous solution at 30 °C containing A and B at concentrations of 1.0 and 1.2 M, respectively, is to be fed to two CSTRs in series at a flow rate of 75 L min^-1^. Reaction (1) will occur in the adiabatic reactors with a rate of reaction that is accurately described by equation (2). The rate coefficient exhibits Arrhenius temperature dependence with a pre-exponential factor of 8.72 x 10^5^ L mol^-1^ min^-1^ and an activation energy of 7200 cal mol^-1^. The heat of reaction (1) is -10,700 cal mol^-1^ and may be assumed to be constant. The heat capacityand the density of the solution may be taken to be constants and equal to those of water (1.0 cal g^-1^ K^-1^ and 1.0 g cm^-3^). If 90% of the A needs to be converted, what is the minimum total volume required, and how is it divided between the two reactors?

$$
A + B \rightarrow Y + Z \tag{1}
$$

$$
r_1 = k_1 C_A C_B \tag{2}
$$

[Example 12.4.3 Solution](examples/12_4_3/Example%2012.4.3.pdf)

[Example 12.4.3 Calculations](examples/12_4_3/example_12_4_3.py)

---

**Example 12.4.4** A liquid phase process that uses a 60 dm^3^ PFR is going to be shut down so that a second 40 dm^3^
PFR can be added to increase throughput. Space constraints dictate that the second reactor will be
added in parallel with the first. The design calls for processing a feed solution containing 1 mol L^-1^ of A at
60 °C and flowing at a rate of 0.55 dm^3^ min^-1^. The solution density may be assumed to be constant. The
reactors will operate adiabatically, at steady state, and with negligible pressure drop. The reaction is irreversible, and the reaction rate is
given in equation (2) where k~0~ = 2.63 x 10^7^ L mol^-1^ min^-1^ and E = 62 kJ mol^-1^. The heat of reaction and the
heat capacity of the solution may be assumed to be constant and equal to -35 kJ mol^-1^ and 800 J L^-1^ K^-1^,
respectively. Compare the conversion when the feed is split equally between the two reactors to the
conversion when the feed is split so that the space times are equal in the two reactors.

$$
2 A \rightarrow Y + Z \tag{1}
$$

$$
r_1 = k_1 C_A^2 \tag{2}
$$

[Example 12.4.4 Solution]()

[Example 12.4.4 Calculations]()

---

**Example 12.4.5** Reaction (1) takes place in an adiabatic, steady state PFR using 750 dm^3^ min^-1^ of a constant-density liquid solution containing the reactant at a concentration of 3.8 mol dm^-3^ and a temperature of 25 °C. Pressure drop in the reactor is neglibible. The heat of reaction is -79.8 kJ mol^-1^, and may be assumed to be constant over the range of temperatures where this reactor operates. The heat capacity of the solution is equal to 987 cal L^-1^ K^-1^, independent of composition and temperature. For a conversion of 80%, compare the required PFR volume without thermal backmixing to that with thermal backmixing, assuming a simple counter-current heat exchanger with U~LM~A = 1500 kJ min^-1^ K^-1^. The rate is first order in the concentration of A, the Arrhenius pre-exponential factor is 3.38 x 10^6^ min^-1^, and the activation energy is 50 kJ mol^-1^.

$$
A \rightarrow Z \tag{1}
$$

[Example 12.4.5 Solution]()

[Example 12.4.5 Calculations]()

---

**Example 12.4.6** An adiabatic PFR with a volume of 4 m^3^ will be used to process 1.25 mol s^-1^ of an equimolar gas phase mixture of A and B at 300 K and 2.5 atm. This feed will be pre-heated using the product stream from the reactor. The heat of reaction is constant and equal to -8,600 cal mol^-1^. The heat capacity of the gas is constant and equal to 25.8 cal mol^-1^ K^-1^. Pressure drop in the reactor is negligible. The heat transfer area multipled by the heat transfer coefficient U~AM~A = 13.6 cal K^-1^ s^-1^. What will the final conversion equal if reaction (1) takes place with a rate given by equation (2) with the pre-exponential factor equal to 8.12 x 10^2^ s^-1^ and the activation energy equal to 9,500 cal mol^-1^.?

$$
A + B \rightarrow Y + Z \tag{1}
$$

$$
r_1 = k_1 C_A \tag{2}
$$

[Example 12.4.6 Solution]()

[Example 12.4.6 Calculations]()

---

**Example 12.4.7** In liquid phase reaction (1) the chiral molecule, Z, is produced auto-catalytically according to the rate expression given in equation (2). In the absence of the product, Z, the reaction rate is very small. The heat of reaction is -14 kcal mol^-1^, independent of temperature. The pre-exponential factor is equal to 4.2 x 10^15^ cm^3^ mol^-1^ min^-1^ and the activation energy is 18 kcal mol^-1^. A solvent is used, and the heat capacity of the reacting solution can be taken to equal that of the solvent, 1.3 cal cm^-3^ K^-1^. The density of the liquid may be assumed to be constant. The concentrations of A and Z in the feed to the process are 2 M and 0 M, respectively, and the flow rate is 500 cm^3^ min^-1^ at 300K. An adiabatic recycle PFR with a recycle ratio of 1.3 is used. The reactor diameter is 5 cm and it is 50 cm long. What are the outlet concentrations of A and Z and the outlet temperature from the process?

$$
A \rightarrow Z \tag{1}
$$

$$
r_1 = k_1C_AC_Z \tag{2}
$$

[Example 12.4.7 Solution]()

[Example 12.4.7 Calculations]()

## Learning Activities from *REB, The Course* {.ch}

{< include activities/class_30/narrative.qmd >}}

add equations

[Learning Activity 30 Solution]()

[Learning Activity 30 Calculations]()

---

{< include activities/class_31/narrative.qmd >}}

add equations

[Learning Activity 31 Solution]()

[Learning Activity 31 Calculations]()

---

{< include activities/class_32/narrative.qmd >}}

add equations

[Learning Activity 32 Solution]()

[Learning Activity 32 Calculations]()

## Practice Assignments from *REB, The Course* {.ch}

{< include practice/class_30/narrative.qmd >}}

add equations

[Practice Assignment 30 Solution]()

[Practice Assignment 30 Calculations]()

---

{< include practice/class_31/narrative.qmd >}}

add equations

[Practice Assignment 31 Solution]()

[Practice Assignment 31 Calculations]()

---

{< include practice/class_32/narrative.qmd >}}

add equations

[Practice Assignment 32 Solution]()

[Practice Assignment 32 Calculations]()

## Additional Assignments for Extra Practice {.ch}

Additional assignments will be added as they become available.

{< include includes/_bottom_license.qmd >}}

